initial version to commit to develop
Metatavu/github-readme-footer-generator pull request #1
Opened 2024-07-04 08:48 UTC by Essomatic

2024-07-04 10:00 UTC, Jdallos requested changes

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +</div>`;
Perhaps the footer could be exported from its own file?

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +    console.error('Error in main function:', error);
```suggestion
    console.error("Error in main function:", error);
```

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +    // displaySelectedRepositories(repositoriesOBJ)
Is this going to be used, if not remove commented code

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +import { config } from "dotenv";
Lets do the whole project in TypeScript

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +async function main() {
Add Docs

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +const ORG = process.env.ORG;
Does this need to be uppercase name? I'd also suggest calling it organization

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +const ORG = process.env.ORG;
Is this actually used in the current version of the code?

2024-07-04 10:00 UTC, Jdallos commented on index.js
> +    await updateReadmeAndAutoMergeRepositories(repositoriesOBJ, footer)
Aha, ok I see. I would suggest removing all the mock related functions and just get the code so that it is how it would actually be run when an ORG is provided.
Let me know if I have misunderstood this, but for now I will ignore any mock related code

2024-07-04 10:00 UTC, Jdallos commented on old/githubUtils.js
> +//THIS is no longer in use, script updates readme with PUT request deprecated by new method making pull requests and automerge
If something is not in use then let's remove it

2024-07-04 10:00 UTC, Jdallos commented on old/githubUtils.js
> +const TOKEN = process.env.GITHUB_TOKEN;
When you switch to TS it will probably make sense to have some kind of env validation done in config to handle whether the token is present or not.

2024-07-04 10:00 UTC, Jdallos commented on old/githubUtils.js
> +// Get environment variables
Commenting code can be a good idea, at minimum we want TSDocs for all functions, also is something is not clear comments can be helpful. However it's clear enough what is happening here so this comment could be removed.

2024-07-04 10:00 UTC, Jdallos commented on old/githubUtils.js
> +//THIS is no longer in use, script updates readme with PUT request deprecated by new method making pull requests and automerge
I won't review this file any more if it's no longer in use

2024-07-04 10:00 UTC, Jdallos commented on package.json
> +    "test": "echo \"Error: no test specified\" && exit 1"
You could add a run script in here

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +import { parse } from 'node-html-parser'
```suggestion
import { parse } from "node-html-parser"
```

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +import { parse } from 'node-html-parser'
Use double quotes and be consistent throughout project

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +export function checkForExistingFooter(content) {
DOCS

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +export function createOrOverwriteFooter(content, footer, forceOverwrite, repo) {
DOCS

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +        console.log("Repository:", repo.toString(), " README was overwriten.")
Lets have consistent use of semi-colons ;

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +    // if we have existing footer and and want to overwrite
Comment not necessary imo

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +    // Return true if footer exists, false otherwise
Comment not necessary imo

2024-07-04 10:00 UTC, Jdallos commented on utils/footerUtils.js
> +    // Wrapper used detecting custom footer
Maybe this comment could be clarified?

2024-07-04 10:00 UTC, Jdallos commented on utils/githubOrganizationUtils.js
> +const TOKEN = process.env.GITHUB_TOKEN;
As mentioned in previous comment some env validation would be nice

2024-07-04 10:00 UTC, Jdallos commented on utils/githubOrganizationUtils.js
> +export async function getOrganizationRepositories(org) {
DOCS

2024-07-04 10:00 UTC, Jdallos commented on utils/githubOrganizationUtils.js
> +export async function getOrganizationRepositories(org) {
Typically within the company we always use arrow functions whereever possible and I would recommend updating all functions to follow this convention

2024-07-04 10:00 UTC, Jdallos commented on utils/githubOrganizationUtils.js
> +export async function getOrganizationRepositories(org) {
Another company convention is to set the indentation spaces to 2

2024-07-04 10:00 UTC, Jdallos commented on utils/githubOrganizationUtils.js
> +}
This can be removed from the PR

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +
no need for double line breaks

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +// Delete branch if it exists, or log if it doesn't
As TSDocs please

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +        console.log("Deleted existing branch:", `\x1b[36m${branchName}\x1b[0m`, "in repository:", `\x1b[35m${repo}\x1b[0m`);
Looks like some funky mark up there, could it be possible to make a named variable/ wrapper for the string to give some clarity as to what the mark up is doing?

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +async function createBranchFromDevelop(owner, repo, branchName) {
DOCs

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +async function fetchReadme(owner, repo) {
I won't comment about Docs anymore

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +        const response = await octokit.request('GET /repos/{owner}/{repo}/contents/{path}', {
Code clarity could be greatly improved by creating a githubService which contains all of the various requests, then here you can just called the named request. In some cases like this fetchReadMe for example the function is already basically the function you would want in the service. But having a service file containing all such functions could be a good way of restructuring to improve clarity in this file. Feel free to disagree

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +    });
These could probably be refactored into another appropriately named function

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +        await octokit.request(`DELETE /repos/${owner}/${repo}/git/refs/heads/${branchName}`);
If the repo already has a footer, will it have a similarly named branch in the past and will this delete it? If so is it necessary. How about some number variation of the branches even creating an issue number (although maybe this is not necessary).

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +    const branchName = 'update-readme';
If the delete branch method currently would delete any previous branches that were done (and indeed merged) I'm not sure that's the best idea. Could this be made unique somehow, perhaps by also creating an issue and adding the issue into the branch name?

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +            console.log("No changes made to", `\x1b[35m${owner}/${repo}\x1b[0m`, "skipping pull request creation.");
Said it in a previous comment but will say it again all of these logs, if the string could be named as a variable to at least give some indication as to what they are doing, if i understand correctly e.g. some semantic value to the coloring of the text.

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +    console.log('\x1b[31m%s\x1b[0m', 'Do you want to overwrite ALL existing metatavu-custom-footers for all repositories? (otherwise will be asked individually) (y/n): ');
I think what antti would like is the option to not only be able to overwrite all at the start but also after each repo be asked again do you want to overrite/ proeceed with all the remaining repos

2024-07-04 10:00 UTC, Jdallos commented on utils/githubUtils.js
> +        console.log("metatavu-custom-footer exists already! Do you want to overwrite the existing footer for", `\x1b[35m${owner}/${repo}\x1b[0m?`,"(y/n)")
I think even if we are not overwriting we would like to be able to individually confirm or cancel for each repo

2024-07-10 05:34 UTC, anttileppa requested changes

2024-07-10 05:34 UTC, anttileppa commented on README.md
> +3. run npm install to get dependencies with command:
Add .nvmrc and a step to ensure that the user is using correct version of nodejs

2024-07-10 05:34 UTC, anttileppa commented on src/index.ts
> +async function main(): Promise<void> {
Add tsdocs

2024-07-10 05:34 UTC, anttileppa commented on src/customFooter.ts
> +// Define the custom footer (will be wrapped inside a custom div for identification)
Use kebab-case for file names

2024-07-10 05:34 UTC, anttileppa commented on src/services/githubServices.ts
> +import { Octokit } from "@octokit/core";
Use kebab-case for file names

2024-07-10 05:34 UTC, anttileppa commented on src/utils/footerUtils.ts
> +import { parse } from "node-html-parser";
Use kebab-case for file names

2024-07-10 05:34 UTC, anttileppa commented on src/utils/githubOrganizationUtils.ts
> +import { config } from "dotenv";
Use kebab-case for file names

2024-07-10 05:34 UTC, anttileppa commented on src/utils/githubUtils.ts
> +import { config } from "dotenv";
Use kebab-case for file names

2024-07-10 05:34 UTC, anttileppa commented on src/services/githubServices.ts
> + */
This seems a lot like a jsdoc comment. Also it does not describe params correctly. 

Here is an example of proper comment (fix all comments in the project before next review): 

```suggestion
/**
 * Gets the specified branch reference.
 * 
 * @param params - The owner and repository name.
 * @param params.owner - The owner of the repository.
 * @param params.repository - The name of the repository.
 * @param branchName - The name of the branch..
 * @returns The response from the GitHub API.
 */
```

2024-07-11 10:24 UTC, anttileppa requested changes

2024-07-11 10:24 UTC, anttileppa commented on src/types/types.ts
> +export interface Repository {
Add tsdocs

2024-07-11 10:24 UTC, anttileppa commented on src/types/types.ts
> +export interface RepositoryStatus extends Repository {
Add tsdocs

2024-07-11 10:24 UTC, anttileppa commented on src/utils/github-organization-utils.ts
> +export async function getOrganizationRepositories(org: string): Promise<Repository[]> {
Name implies that it returns all repositories but it actually returns just public repos.

2024-07-11 10:24 UTC, anttileppa commented on src/utils/github-utils.ts
> +    await getBranch(repositoryOBJ, branchName);
Should we check the existence of the branch before attempting to delete it?

2024-07-11 10:24 UTC, anttileppa commented on src/utils/utils.ts
> +/**
This could be replaced with something like:

    /**
     * Enum for log colors.
     */
    export enum LogColor {
      PURPLE = '\x1b[35m',
      CYAN = '\x1b[36m',
      RED = '\x1b[31m',
      GREEN = '\x1b[32m',
      ORANGE = '\x1b[38;5;214m'
    }
    
    /**
     * Wraps a string in the specified color.
     * 
     * @param text - The text to color.
     * @param color - The color code to wrap the text in.
     * @returns The text wrapped in the specified color codes.
     */
    export const log = (text: string, color: LogColor): string => {
      return `${color}${text}\x1b[0m`;
    };

but actually you should use something like chalk (npmjs.com/package/chalk) to do terminal string styling

2024-07-11 10:24 UTC, anttileppa commented on src/utils/utils.ts
> +function isValidRepository(repositoryOBJ: Repository): boolean {
What does valid mean in this context? I would assume that all repositories that are in GitHub are actually valid but this probably means something else?

2024-07-11 10:32 UTC, Essomatic commented on src/utils/github-utils.ts
> +    await getBranch(repositoryOBJ, branchName);
We are checking with the getBranch if the branch does not exist we get 404 error that is handled differently in the catch

2024-07-11 10:41 UTC, Essomatic commented on src/utils/utils.ts
> +function isValidRepository(repositoryOBJ: Repository): boolean {
mainly needed for the env override repos because they are typed manually and managed to run script with invalid data so saw firsthand this could be useful, but everything else is also validated since it does no harm to check that the data does exist and has all the needed fields

2024-07-11 11:10 UTC, Essomatic commented on src/utils/utils.ts
> +/**
I would prefer using the individual functions like logRed, logGreen, etc. over the Enum, they seem intuitive to me and when I see logRed("red text"), it's immediately clear what is happening. only downside is multiple functions in the utils but they are simple and don't see it as such drawback. In the first review I told Josh I kept the script as vanilla and having few dependency's as possible, but I asked if we wanted to use some library for this and he agreed it might be overkill, but you are the one who decides.

2024-07-16 17:23 UTC, anttileppa requested changes

2024-07-16 17:23 UTC, anttileppa commented on src/index.ts
> +const overideRepositoriesJSON: string | undefined = process.env.OVERRIDE_REPOS;
It would be better to use separate config class for handling configuration.

2024-07-16 17:23 UTC, anttileppa commented on src/index.ts
> +const overideRepositoriesJSON: string | undefined = process.env.OVERRIDE_REPOS;
Also use envalid (https://www.npmjs.com/package/envalid) to validate environment variables

2024-07-16 17:23 UTC, anttileppa commented on src/index.ts
> +function checkEnvironmentVariables(): void {
Replace this with previously mentioned envalid

2024-07-16 17:23 UTC, anttileppa commented on src/utils/github-utils.ts
> +    await getBranch(repositoryOBJ, branchName);
ok, fair enough, although it would be easier to read if this would be something like

```suggestion
    if (!await isExistingBranch(repositoryOBJ, branchName)) {
       console.log("Branch", logCyan(branchName), "does not exist in repository", logPurple(repoName), "Proceeding...");
       return;
    }
```

2024-07-16 17:23 UTC, anttileppa commented on src/utils/github-utils.ts
> +async function createAndCommit(repositoriesOBJ: Repository, branchName: string, base64UpdatedContent: string): Promise<boolean> {
Why this is not an arrow function, when every other function in the file seem to be?

2024-07-16 17:23 UTC, anttileppa commented on src/utils/utils.ts
> +/**
Unpackaged size of Chalk is 43.7 kB, so it adds very little extra to the app, so from my perspective writing something yourself and maintaining it sounds bigger issue than adding dependency that already handles this and much more

2024-07-17 07:36 UTC, Essomatic commented on src/utils/github-utils.ts
> +    await getBranch(repositoryOBJ, branchName);
I changed it to this

2024-07-17 07:56 UTC, Essomatic commented on src/utils/utils.ts
> +/**
that is true, switched to it

2024-07-25 10:28 UTC, anttileppa requested changes

2024-07-25 10:28 UTC, anttileppa commented on src/index.ts
> +    if (overrideRepositories) {
```suggestion
    if (overrideRepositories && overrideRepositories.length > 0) {
```

2024-08-14 06:37 UTC, Jdallos requested changes

2024-08-14 06:37 UTC, Jdallos commented on README.md
>  This script is used to generate custom footer component under public repositories of organization. The script can detect presense of previosly added footer components and user is promted to either ov
```suggestion
This script is used to generate custom footer component under public repositories of organization. The script can detect presence of previously added footer components and user is prompted to either overwrite or skip these repositories, so the script SHOULD be safe to run multiple times.
```

2024-08-14 06:37 UTC, Jdallos commented on footerExamplest.txt
Should this file be named footerExamples.txt?

2024-08-14 06:37 UTC, Jdallos commented on src/config.ts
> +import { Repository } from './types/types';
Double quotes. If you wanted you could set up a linter e.g. biome in this project, but it's not essential.

2024-08-14 06:37 UTC, Jdallos commented on src/custom-footer.ts
> +  <h2>Example</h2>
Is this h2 needed?

2024-08-14 06:37 UTC, Jdallos commented on src/custom-footer.ts
> +`<div align="center">
Double quotes?

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +import { config } from './config';
Consistent use of double quotes.

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +async function main(): Promise<void> {
Typically we use arrow functions, is there a reason not to use one here?

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +
```suggestion
```

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +    if (overrideRepositories && overrideRepositories.length != 0) {
```suggestion
    if (overrideRepositories && overrideRepositories.length !== 0) {
```

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +    } else if ((loadedFromFile = promptAndLoadFailedRepositories())) {
Should this be === ?
Otherwise aren't you assigning?

If it should be = then could this assign be done before the conditionals and then used as a variable rather than assigning within the conditional

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +const overrideRepositories: Repository[] = config.OVERRIDE_REPOS;
Do these need to be explicitly typed if you are using envalid?

2024-08-14 06:37 UTC, Jdallos commented on src/index.ts
> +      repositoriesOBJ = await getOrganizationPublicRepositories(organization!);
Are you sure organization needs to be asserted with ! here? Isn't envalid validating this?

2024-08-14 06:37 UTC, Jdallos commented on src/services/github-services.ts
> +export const getBranch = async ({ owner, repository }: Repository, branchName: string): Promise<any> => {
Could it be worth using https://github.com/octokit/types.ts (or some better alternative) so you have access to Octokit types and the return type could be more specific than any for these various functions?

2024-08-14 06:37 UTC, Jdallos commented on src/services/github-services.ts
> + * @param branchName - The name of the branch.
```suggestion
 * @param owner - The owner of the repository.
 * @param repository - The name of the repository.
 * @param branchName - The name of the branch.
```

2024-08-14 06:37 UTC, Jdallos commented on src/services/github-services.ts
> + * @param branchName - The name of the branch.
This suggestion is more typical for TSDocs, if  you agree then update for the various functions where you had the previous params.something comments (alll the functions below)

2024-08-14 06:37 UTC, Jdallos commented on src/services/github-services.ts
> +      mode: "100644",
What does this mode value do/ mean?

2024-08-14 06:37 UTC, Jdallos commented on src/services/github-services.ts
> +      'X-GitHub-Api-Version': '2022-11-28'
Is this a value that might need updating in the future?

2024-08-14 06:37 UTC, Jdallos commented on src/types/types.ts
> + *
```suggestion
```

2024-08-14 06:37 UTC, Jdallos commented on src/types/types.ts
> + *
```suggestion
```

2024-08-14 06:37 UTC, Jdallos commented on src/utils/footer-utils.ts
> +import chalk from 'chalk';
Consistent double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/footer-utils.ts
> +export const checkForExistingFooter = (content: string): boolean => {
Generally if the return type can be automatically inferred correctly by TS (check by hovering over the function name in VSCode) we don't explicitly declare the return type. So in this case the return type : boolean can be removed

2024-08-14 06:37 UTC, Jdallos commented on src/utils/footer-utils.ts
> +  const dom = parse(content);
Can this dom const be typed?

2024-08-14 06:37 UTC, Jdallos commented on src/utils/footer-utils.ts
> +  const dom = parse(content);
You might need to look for an @types for the node-html-parser, if it doesn't exist then there isn't much we can do!

2024-08-14 06:37 UTC, Jdallos commented on src/utils/footer-utils.ts
> +export const shouldOverwriteFooter = (repositoriesOBJ: Repository, originalContent: string, overwriteExistingFooter: boolean): boolean => {
Another example of the explicit return type not being needed

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +import chalk from 'chalk';
Consistent double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +const updateBranchName: string = config.UPDATE_BRANCH_NAME;
Explict type not needed

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> + * @param repositoryOBJ.repository - The name of the repository.
If you are not destructuring the repositoryOBJ in the params then there is no need to add the owner and repository as Docs. Similar changes should be made to Docs in the functions below

Also when you have a type for an param I would typically write the doc like:
@param repositoryOBJ Repository 
But this way is fine here and doesn't need to be changed

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +  if (!await isExistingBranch(repositoryOBJ, branchName)) {
For code clarity I could create a variable from the awaited return value rather than evaluating it within the conditional

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +const isExistingBranch = async (repositoryOBJ: Repository, branchName: string): Promise<boolean> => {
Explicit return type not needed?

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +  } catch (error: any) {
Is there a more specific typing for the error than any?

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +const createBranchFromDevelop = async (repositoryOBJ: Repository, branchName: string): Promise<{ hasDevelop: boolean }> => {
No need for explicit return typing here. But wouldn't it be simpler to just return a boolean rather than the object?

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +const updateReadme = async (repositoryOBJ: Repository, branchName: string, footer: string, overwriteExistingFooter: boolean): Promise<{ updated: boolean }> => {
Same as above, is there a good reason to not just return a boolean rather than an object?

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +    const latestCommit = latestCommitResponse.data as { object: { sha: string } };
Hopefully if you can type the octokit responses then these castings will no longer be required

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +      case 'skipped':
Double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/github-utils.ts
> +const displaySummary = (repositoryStatuses: { owner: string; repository: string; status: string; message: string }[]) => {
Use the RepositoryStatus[] type

2024-08-14 06:37 UTC, Jdallos commented on src/utils/repository-error-file-utils.ts
> +import fs from 'fs';
Double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/repository-error-file-utils.ts
> +  const filePath = 'failed-repositories.json';
Double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/repository-error-file-utils.ts
> +      const fileContent = fs.readFileSync(filePath, 'utf8');
Double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/repository-error-file-utils.ts
> +    .filter(repoStatus => repoStatus.status === 'failed')
Double quotes

2024-08-14 06:37 UTC, Jdallos commented on src/utils/repository-error-file-utils.ts
> +  fs.writeFileSync(filePath, jsonContent, 'utf8');
Double quotes

2024-08-14 07:45 UTC, Essomatic commented on src/services/github-services.ts
> +      mode: "100644",
https://git-scm.com/book/sv/v2/Git-Internals-Git-Objects

"In this case, you’re specifying a mode of 100644, which means it’s a normal file. Other options are 100755, which means it’s an executable file; and 120000, which specifies a symbolic link. The mode is taken from normal UNIX modes but is much less flexible — these three modes are the only ones that are valid for files (blobs) in Git (although other modes are used for directories and submodules)."

2024-08-14 07:51 UTC, Essomatic commented on src/services/github-services.ts
> + * @param branchName - The name of the branch.
can we get definitive format. [https://github.com/Metatavu/github-readme-footer-generator/pull/1#discussion_r1671643426](https://github.com/Metatavu/github-readme-footer-generator/pull/1#discussion_r1671643426)

2024-08-14 07:54 UTC, Essomatic commented on src/custom-footer.ts
> +  <h2>Example</h2>
It is an example.

2024-08-14 08:06 UTC, Essomatic commented on src/services/github-services.ts
> +      'X-GitHub-Api-Version': '2022-11-28'
https://docs.github.com/en/rest/about-the-rest-api/api-versions?apiVersion=2022-11-28

Its the current version and only supported version. any breaking changes gets a new versions, but if they do update with breaking changes I would assume the whole code needs changes not only this header.

2024-08-14 08:34 UTC, Essomatic commented on src/index.ts
> +    } else if ((loadedFromFile = promptAndLoadFailedRepositories())) {
It is assigning and I cant see a clear way to run it before the conditionals because we want it to happen just as we enter the else if not before. The logic could be somewhat changed and run partly inside the else if block, but I see this current code as better option.

2024-08-15 11:52 UTC, Jdallos approved these changes

2024-08-30 04:58 UTC, anttileppa approved these changes

2024-09-09 09:11 UTC, merged